# Generated by Django 5.2.6 on 2025-09-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0002_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(default="Unknown", max_length=500),
            preserve_default=False,
        ),
    ]
